# 张量（Tensor）
## 本代码脚本讲解 Tensorflow 中创建张量（tensor）的各种方式

首先，让我们加载 Tensorflow 并重置计算图。

【译者注：张量(https://zh.wikipedia.org/wiki/%E5%BC%B5%E9%87%8F) 是一个可用来表示在一些矢量、标量和其他张量之间的线性关系的多线性函数，这些线性关系的基本例子有内积、外积、线性映射以及笛卡儿积。其坐标在  n  维空间内，有  n^r 个分量的一种量，其中每个分量都是坐标的函数，而在坐标变换时，这些分量也依照某些规则作线性变换。r 称为该张量的秩或阶（与矩阵的秩和阶均无关系）。】

In [1]:
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

### 开始一个计算图会话
通过`tf.Session()`来获取计算图

In [2]:
sess = tf.Session()

### 创建张量（Tensor）
TensorFlow内置了函数来创建张量，并用于变量。例如，我们可以使用`tf.zeros()`函数，创建一个预定义形状的零填充张量。如下所示：

In [3]:
my_tensor = tf.zeros([1,20])

我们可以在会话中调用`run()`方法来计算张量。

In [4]:
sess.run(my_tensor)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

Tensorflow 算法需要知道哪些对象是变量(variable)，哪些是常量(constant)。关于这两个对象之间的区别将在后面的章节中解释。现在我们用 TensorFlow 的`tf.Variable()`函数创建一个变量。如下所示：

In [5]:
my_var = tf.Variable(tf.zeros([1,20]))

注意！现在不能运行`sess.run(my_var)`，这会出错。因为 TensorFlow 使用计算图进行操作，这必须先创建变量初始化操作后再计算变量。稍后我们会看到更多这样的内容。对于这个脚本，我们可以通过调用变量的方法`my_var.initializer`来一次初始化一个变量。

In [6]:
sess.run(my_var.initializer)
sess.run(my_var)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

现在，我们先声明行和列的大小，再创建特定形状的变量

In [7]:
row_dim = 2
col_dim = 3

下面是变量被初始化为全零或全一。

In [8]:
zero_var = tf.Variable(tf.zeros([row_dim, col_dim]))
ones_var = tf.Variable(tf.ones([row_dim, col_dim]))

再次，我们可以在变量上调用初始化方法，并运行它们来计算它们的内容。

In [9]:
sess.run(zero_var.initializer)
sess.run(ones_var.initializer)
print(sess.run(zero_var))
print(sess.run(ones_var))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


### 基于其他张量的形状来创建张量
如果张量的形状取决于另一个张量的形状，那么我们可以使用 TensorFlow 内置函数`ones_like()`或`zeros_like()`。

In [10]:
zero_similar = tf.Variable(tf.zeros_like(zero_var))
ones_similar = tf.Variable(tf.ones_like(ones_var))

sess.run(ones_similar.initializer)
sess.run(zero_similar.initializer)
print(sess.run(ones_similar))
print(sess.run(zero_similar))

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 用常量（constant）来填充张量（tensor)
下面是如何用常量来填充张量。

In [11]:
fill_var = tf.Variable(tf.fill([row_dim, col_dim], -1))
sess.run(fill_var.initializer)
print(sess.run(fill_var))

[[-1 -1 -1]
 [-1 -1 -1]]


我们也可以从常量数组或常量列表来创建一个变量。

In [12]:
# 用常量来创建变量
const_var = tf.Variable(tf.constant([8, 6, 7, 5, 3, 0, 9]))
# 这同样可以被用来填充数组
const_fill_var = tf.Variable(tf.constant(-1, shape=[row_dim, col_dim]))

sess.run(const_var.initializer)
sess.run(const_fill_var.initializer)

print(sess.run(const_var))
print(sess.run(const_fill_var))

[8 6 7 5 3 0 9]
[[-1 -1 -1]
 [-1 -1 -1]]


### 基于序列和范围创建张量
在 TensorFlow 中，我们可以用序列生成函数来创建张量。TensorFlow 的`linspace()`和`range()`函数的操作非常类似于 python/numpy 的对应函数。

In [13]:
# TensorFlow 的 Linspace
linear_var = tf.Variable(tf.linspace(start=0.0, stop=1.0, num=3)) # 生成 [0.0, 0.5, 1.0] ，包含尾数1.0

# TensorFlow 的 Range
sequence_var = tf.Variable(tf.range(start=6, limit=15, delta=3)) # 生成 [6, 9, 12]，不包含尾数15

sess.run(linear_var.initializer)
sess.run(sequence_var.initializer)

print(sess.run(linear_var))
print(sess.run(sequence_var))

[0.  0.5 1. ]
[ 6  9 12]


### 张量中的随机数
我们也可以用随机数，来初始化张量，如下所示。

In [14]:
rnorm_var = tf.random_normal([row_dim, col_dim], mean=0.0, stddev=1.0)
runif_var = tf.random_uniform([row_dim, col_dim], minval=0, maxval=4)

print(sess.run(rnorm_var))
print(sess.run(runif_var))

[[-1.2880906   0.5628729   0.29671913]
 [-0.89132464  1.325848    0.43309394]]
[[2.2251906  1.4528546  1.0023308 ]
 [2.782339   0.21443892 1.9388914 ]]


### 用 TensorBoard 来可视化变量的创建过程
为了在 Tensorboard中 可视化变量的创建过程（在第11章中详细介绍），我们将重置计算图并创建一个全局初始化操作。

In [15]:
# 重置计算图
ops.reset_default_graph()

# 开启一个计算图会话
sess = tf.Session()

# 创建变量
my_var = tf.Variable(tf.zeros([1,20]))

# 为tensorboard添加概述
merged = tf.summary.merge_all()

# 初始化计算图写入器
writer = tf.summary.FileWriter("/tmp/variable_logs", graph=sess.graph)

# 全局初始化操作
initialize_op = tf.global_variables_initializer()

# 运行变量的初始化操作
sess.run(initialize_op)

现在，我们在命令行中运行如下命令：

`tensorboard --logdir=/tmp`

紧接着，它会告诉我们，可以在浏览器来查看 Tensorboard 的地址。 默认值应该是：

`http://0.0.0.0:6006/`

![Variable_in_Tensorboard](https://github.com/nfmcclure/tensorflow_cookbook/raw/master/01_Introduction/images/02_variable.png)