# 矩阵和矩阵运算

接下来将要介绍如何创建矩阵（matrix）并在 TensorFlow 中使用。

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

开始一个计算图会话（graph session）

In [2]:
sess = tf.Session()

### 声明矩阵

单位阵：

In [3]:
identity_matrix = tf.diag([1.0,1.0,1.0])  # diagonal 对角矩阵
print(sess.run(identity_matrix))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


随机的 2x3 正态分布矩阵：

In [4]:
A = tf.truncated_normal([2,3])
print(sess.run(A))

[[-0.51852965 -0.40482247 -1.042013  ]
 [ 0.2788375  -0.17284071 -1.073788  ]]


2x3 常量矩阵：

In [5]:
B = tf.fill([2,3], 5.0)
print(sess.run(B))

[[5. 5. 5.]
 [5. 5. 5.]]


3x2 随机 均匀分布 矩阵：

In [6]:
C = tf.random_uniform([3,2])
print(sess.run(C))

[[0.42939377 0.6303717 ]
 [0.41271734 0.79922676]
 [0.7075918  0.3374859 ]]


用 np array 创建 矩阵：

In [7]:
D = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]]))
print(sess.run(D))

[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


### 矩阵运算（Matrix Operations）

矩阵 加法、减法：

In [8]:
print(sess.run(A+B))
print(sess.run(B-B))

[[4.501319  4.53403   4.9432645]
 [4.4578524 3.1183228 3.5637214]]
[[0. 0. 0.]
 [0. 0. 0.]]


矩阵乘法：

In [9]:
print(sess.run(tf.matmul(B, identity_matrix)))

[[5. 5. 5.]
 [5. 5. 5.]]


矩阵转置：

In [15]:
print(sess.run(tf.transpose(C)))
print(sess.run(tf.transpose(D)))

[[0.3642304  0.6026764  0.8993485 ]
 [0.41105366 0.5909133  0.37020564]]
[[ 1. -3.  0.]
 [ 2. -7.  5.]
 [ 3. -1. -2.]]


矩阵（方阵）行列式：

In [11]:
print(sess.run(tf.matrix_determinant(D)))

-37.99999999999999


矩阵的逆：

In [12]:
print(sess.run(tf.matrix_inverse(D)))

[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


Cholesky 分解：

In [13]:
print(sess.run(tf.cholesky(identity_matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


特征值（Eigenvalues）和特征向量（Eigenvectors）：`tf.self_adjoint_eig()` 函数，返回2个对象：一个特征值数组和一个对应的特征向量矩阵。

In [14]:
eigenvalues, eigenvectors = sess.run(tf.self_adjoint_eig(D))
print(eigenvalues)
print(eigenvectors)

[-10.65907521  -0.22750691   2.88658212]
[[ 0.21749542  0.63250104 -0.74339638]
 [ 0.84526515  0.2587998   0.46749277]
 [-0.4880805   0.73004459  0.47834331]]
