# 占位符（Placeholder）

我们将要介绍如何在 TensorFlow 中使用占位符（placeholder）。

首先，让我们引入必要的库并重置计算图（graph session）。

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

开始一个计算图（graph session）。

In [2]:
sess = tf.Session()

### 声明占位符

我们用 TensorFlow 的`tf.placeholder()`函数来创建声明一个占位符。这个函数接受一个数据类型（data-type）参数（如：`tf.float32`）和一个形状（shape）参数（如：`(4,4)`）。注意：形状参数可以是一个元组（tuple）`(4,4)`或一个列表（list）`[4,4]`。

In [3]:
x = tf.placeholder(tf.float32, shape=(4, 4))

为了解释清楚如何使用占位符（placeholder），我们创建一个输入数据集和一个在Tensorboard上可视化的运算。
注意`feed_dict`的用法：通过这个我们将`x`的值传入计算图。

In [4]:
# 占位符的输入数据集。注意：'rand_array'和'x'具有相同的形状。
rand_array = np.random.rand(4, 4)

# 创建一个张量（tensor）来执行一个运算。 (y 等于 x，一个 4x4 的矩阵)
y = tf.identity(x)  # 【译者注：idetentity 单位矩阵】

# 打印输出，将 x 喂给计算图
print(sess.run(y, feed_dict={x: rand_array}))

[[ 0.1175806   0.88121527  0.00815445  0.93555111]
 [ 0.97369134  0.14595009  0.16398087  0.76570976]
 [ 0.67633879  0.11748746  0.01266815  0.32564184]
 [ 0.99007022  0.6825515   0.54524553  0.01503101]]


为了在 Tensorboard 中可视化，我们合并摘要并写入日志文件。

In [8]:
merged = tf.summary.merge_all()
writer = tf.summary.FileWriter("/tmp/variable_logs", sess.graph)

在终端中运行如下所示的命令：

`tensorboard --logdir=/tmp`

我们可以在谷歌浏览器中输入以下地址，来查看可视化的计算图。默认地址为：

`http://0.0.0.0:6006/`

![Placeholders_in_Tensorboard](https://github.com/nfmcclure/tensorflow_cookbook/raw/master/01_Introduction/images/03_placeholder.png)